"""added fastTravel column to races

Revision ID: 0aee0b47a27b
Revises: bf0782ac2f23
Create Date: 2026-06-19 11:49:39.334075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aee0b47a27b'
down_revision = 'bf0782ac2f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fastTravel', sa.String(), server_default='Unknown', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('fastTravel')

    # ### end Alembic commands ###
