"""added (weekday,startTime) unique constraint on RaceTime

Revision ID: 7659f452cb44
Revises: 74c5c6a2040d
Create Date: 2026-04-22 12:27:10.485590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7659f452cb44'
down_revision = '74c5c6a2040d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_times', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_race_times_weekday_start_time', ['weekday', 'start_time_local'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_times', schema=None) as batch_op:
        batch_op.drop_constraint('uq_race_times_weekday_start_time', type_='unique')

    # ### end Alembic commands ###
