"""added image paths to Races

Revision ID: bf0782ac2f23
Revises: 7659f452cb44
Create Date: 2026-06-18 14:54:56.485986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0782ac2f23'
down_revision = '7659f452cb44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('locationImageUrl', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('locationImageUrl')
        batch_op.drop_column('imageUrl')

    # ### end Alembic commands ###
